apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempostack
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/hpvolumes
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  volumeMode: Filesystem
