apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traces-writer-user
rules:
  - apiGroups:
      - tempo.grafana.com
    resourceNames:
      - traces
    resources:
      - user
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traces-writer-user-tempostack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traces-writer-user
subjects:
  - kind: ServiceAccount
    name: user-collector
    namespace: tempo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sattributes-otel-collector
rules:
  - apiGroups: ['*']
    resources: ['pods', 'namespaces', 'replicasets']
    verbs: ['get', 'watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sattributes-collector-tempo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8sattributes-otel-collector
subjects:
  - kind: ServiceAccount
    name: user-collector
    namespace: tempo
---
